{
	"version": 1563108164,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bird-sheet0.png",
		"images/bird-sheet1.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/background-sheet0.png",
		"images/bottompipe-sheet0.png",
		"images/toppipe-sheet0.png",
		"images/sprite-sheet0.png",
		"images/play-sheet0.png",
		"images/flappytitulo-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/gamemode-sheet0.png",
		"images/gameover-sheet0.png",
		"images/retry-sheet0.png",
		"images/retry-sheet1.png",
		"media/flap.ogg",
		"media/split.ogg",
		"media/bug splat song.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}